{
  "hoistedDependencies": {},
  "hoistPattern": [],
  "included": {
    "dependencies": true,
    "devDependencies": true,
    "optionalDependencies": true
  },
  "injectedDeps": {},
  "ignoredBuilds": [
    "esbuild@0.25.12",
    "msw@2.12.1(@types/node@24.10.0)(typescript@5.9.3)",
    "bufferutil@4.0.9",
    "es5-ext@0.10.64",
    "utf-8-validate@5.0.10"
  ],
  "layoutVersion": 5,
  "nodeLinker": "isolated",
  "packageManager": "pnpm@10.29.3",
  "pendingBuilds": [],
  "publicHoistPattern": [],
  "prunedAt": "Thu, 12 Feb 2026 00:02:18 GMT",
  "registries": {
    "default": "https://registry.npmjs.org/",
    "@jsr": "https://npm.jsr.io/"
  },
  "skipped": [
    "@esbuild/aix-ppc64@0.25.12",
    "@esbuild/android-arm64@0.25.12",
    "@esbuild/android-arm@0.25.12",
    "@esbuild/android-x64@0.25.12",
    "@esbuild/darwin-arm64@0.25.12",
    "@esbuild/darwin-x64@0.25.12",
    "@esbuild/freebsd-arm64@0.25.12",
    "@esbuild/freebsd-x64@0.25.12",
    "@esbuild/linux-arm64@0.25.12",
    "@esbuild/linux-arm@0.25.12",
    "@esbuild/linux-ia32@0.25.12",
    "@esbuild/linux-loong64@0.25.12",
    "@esbuild/linux-mips64el@0.25.12",
    "@esbuild/linux-ppc64@0.25.12",
    "@esbuild/linux-riscv64@0.25.12",
    "@esbuild/linux-s390x@0.25.12",
    "@esbuild/netbsd-arm64@0.25.12",
    "@esbuild/netbsd-x64@0.25.12",
    "@esbuild/openbsd-arm64@0.25.12",
    "@esbuild/openbsd-x64@0.25.12",
    "@esbuild/openharmony-arm64@0.25.12",
    "@esbuild/sunos-x64@0.25.12",
    "@esbuild/win32-arm64@0.25.12",
    "@esbuild/win32-ia32@0.25.12",
    "@esbuild/win32-x64@0.25.12",
    "@rollup/rollup-android-arm-eabi@4.53.1",
    "@rollup/rollup-android-arm64@4.53.1",
    "@rollup/rollup-darwin-arm64@4.53.1",
    "@rollup/rollup-darwin-x64@4.53.1",
    "@rollup/rollup-freebsd-arm64@4.53.1",
    "@rollup/rollup-freebsd-x64@4.53.1",
    "@rollup/rollup-linux-arm-gnueabihf@4.53.1",
    "@rollup/rollup-linux-arm-musleabihf@4.53.1",
    "@rollup/rollup-linux-arm64-gnu@4.53.1",
    "@rollup/rollup-linux-arm64-musl@4.53.1",
    "@rollup/rollup-linux-loong64-gnu@4.53.1",
    "@rollup/rollup-linux-ppc64-gnu@4.53.1",
    "@rollup/rollup-linux-riscv64-gnu@4.53.1",
    "@rollup/rollup-linux-riscv64-musl@4.53.1",
    "@rollup/rollup-linux-s390x-gnu@4.53.1",
    "@rollup/rollup-openharmony-arm64@4.53.1",
    "@rollup/rollup-win32-arm64-msvc@4.53.1",
    "@rollup/rollup-win32-ia32-msvc@4.53.1",
    "@rollup/rollup-win32-x64-gnu@4.53.1",
    "@rollup/rollup-win32-x64-msvc@4.53.1",
    "fsevents@2.3.3"
  ],
  "storeDir": "/root/.local/share/pnpm/store/v10",
  "virtualStoreDir": ".pnpm",
  "virtualStoreDirMaxLength": 120
}